apiVersion: v1
kind: Service
metadata:
  name: aip-tower-web
  namespace: effyic
  labels:
    app.kubernetes.io/name: aip-tower-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: effyic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aip-tower-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
